---
- name: Copy weave
  copy: 
    dest: /usr/local/bin/weave
    src: weave
    mode: 0755      

- name: Copy weave env script
  copy: 
    dest: /etc/profile.d/weave-env.sh
    src: weave-env.sh
    mode: 0644

- name: Include "{{weave_type_of_node}}" weave recipe
  include: "{{weave_type_of_node}}.yml"